### ISSUE TITLE
Conflict with marcotcr/lime

### ISSUE THREAD

**Issue by jamesmyatt** [oracle/Skater#269]
The dependency on your ds-lime fork creates a conflict with the original marcotcr/lime library, which is now far ahead of your fork. Your fork hasn't been updated in nearly 1.5 years.

Can you consider either:
* Contributing your changes to the original lime library and depend on that, or
* Vendoring the lime library inside skater.

I suppose that an alternative would be to rename the module in ds-lime to avoid the conflict, but I don't recommend it.

Otherwise, it is impossible to have both lime and skater installed in the same virtual environment.

**Comment by pramitchoudhary** [comment]
@jamesmyatt the project is currently in standby mode and the principal contributors are not in active development mode. Apologies for the inconvenience. Let me see if the forked dependency could be resolved. Will update.

**Comment by jklaise** [comment]
@jamesmyatt that's a shame, are there any ETAs on the decisions of what will happen to the library? Also it would be useful to have this flagged on the main readme.

**Comment by jamesmyatt** [comment]
@pramitchoudhary I've looked at merging the ds-lime fork into the upstream library and there are no changes to keep. Can the dependency be updated to use the upstream library?
