### ISSUE TITLE
Paper discussing how skater works

### ISSUE THREAD

**Issue by fabiomercorio** [oracle/Skater#276]
Hi
I would gently ask to know if exists a paper that describes how skater works, or which techniques it employs, otherwise one uses a black box algorithm to explain another black box ones.

Thank you!

**Comment by darenr** [comment]
probably a good place to start would be here: [Understanding model predictions with LIME](https://towardsdatascience.com/understanding-model-predictions-with-lime-a582fdff3a3b) that blog also links to the original LIME paper.
